import type { Metadata } from "next";
import { openSans } from "@/app/ui/fonts";
import { GoogleAnalytics, GoogleTagManager } from "@next/third-parties/google";
import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL(process.env.BASE_URL || ""),
  alternates: {
    canonical: "/",
    languages: {
      "en-US": "/en-US",
    },
  },
  title: {
    default: "United4Digital",
    template: "%s - United 4 Digital",
  },
  description: "Generated by create next app",
  twitter: {
    card: "summary_large_image",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          id="Cookiebot"
          src="https://consent.cookiebot.com/uc.js"
          data-cbid="bf1218b1-b997-4221-94b8-3147efd1b6f5"
          data-blockingmode="auto"
          type="text/javascript"
        ></script>
      </head>
      {/* <GoogleTagManager gtmId="G-FPHQXNL5SQ" />
      <GoogleAnalytics gaId="G-FPHQXNL5SQ" /> */}
      <body
        className={`${openSans.variable} flex flex-col min-h-screen antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
